//@ui5-bundle desafio/l4e/app/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"desafio/l4e/app/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","desafio/l4e/app/model/models"],function(e,i,t){"use strict";return e.extend("desafio.l4e.app.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"desafio/l4e/app/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("desafio.l4e.app.controller.App",{onInit:function(){}})});
},
	"desafio/l4e/app/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("desafio.l4e.app.controller.BaseController",{getRouter:function(){return this.getOwnerComponent().getRouter()},getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)}})});
},
	"desafio/l4e/app/controller/CadastroPlataformas.controller.js":function(){sap.ui.define(["./BaseController","sap/ui/model/json/JSONModel","sap/m/MessageBox"],function(t,a,e){"use strict";return t.extend("desafio.l4e.app.controller.CadastroPlataformas",{onInit:function(){this.getRouter().getRoute("CadastroPlataformas").attachPatternMatched(this.handleRouteMatched,this);this.getRouter().getRoute("EditarPlataformas").attachPatternMatched(this.handleRouteMatchedEditarPlataformas,this)},handleRouteMatched:function(){this.getView().setModel(new a({status:"A"}),"Plataformas")},handleRouteMatchedEditarPlataformas:async function(){var t=this;var s=this.getRouter().getHashChanger().getHash().split("/")[1];this.getView().setBusy(true);await $.ajax({url:`/api/plataformas/${s}`,method:"GET",success(e){t.getView().setModel(new a(e),"Plataformas")},error(){e.error("Não foi possível buscar a plataforma.")}});this.getView().setBusy(false)},onChangeSwitch:function(t){this.getView().getModel("Plataformas").setProperty("/status",t.getSource().getState()===true?"A":"I")},onConfirmar:async function(){var t=this.getView().getModel("Plataformas").getData();var a=this;if(this.getRouter().getHashChanger().getHash().search("EditarPlataformas")===0){await $.ajax(`/api/plataformas/${t.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},data:JSON.stringify({nome:t.nome,status:t.status}),success(){e.success("Editado com sucesso!",{onClose:function(){a.getRouter().navTo("ConsultaPlataformas")}})},error(){e.error("Não foi possível editar a plataforma.")}})}else{this.getView().setBusy(true);await $.ajax("/api/plataformas",{method:"POST",headers:{"Content-Type":"application/json"},data:JSON.stringify(t),success(){e.success("Salvo com sucesso!")},error(){e.error("Não foi possível salvar a plataforma.")}});this.getView().setBusy(false)}},onCancelar:function(){if(this.getRouter().getHashChanger().getHash().search("EditarPlataformas")===0){this.getRouter().navTo("ConsultaPlataformas")}else{this.getView().setModel(new a({status:"A"}),"Plataformas")}}})});
},
	"desafio/l4e/app/controller/ConsultaPlataformas.controller.js":function(){sap.ui.define(["./BaseController","sap/ui/model/json/JSONModel","sap/m/MessageBox","sap/ui/model/Filter","sap/ui/model/FilterOperator"],function(t,a,e,o,s){"use strict";return t.extend("desafio.l4e.app.controller.ConsultaPlataformas",{onInit:function(){this.getRouter().getRoute("ConsultaPlataformas").attachPatternMatched(this.handleRouteMatched,this)},handleRouteMatched:async function(){var t=this;$.ajax({url:"/api/plataformas",method:"GET",success(e){t.getView().setModel(new a(e),"Plataformas")},error(){}})},onExcluir:async function(t){var a=t.getParameter("listItem").getBindingContext("Plataformas").getObject().id;this.getView().setBusy(true);await $.ajax({url:`/api/plataformas/${a}`,method:"DELETE",success(t){e.success("Excluído com Sucesso!")},error(){e.error("Não foi possível excluir a Plataforma.")}});await this.handleRouteMatched();this.getView().setBusy(false)},onNavEditarPlataforma:function(t){var a=t.getSource().getBindingContext("Plataformas").getObject().id;this.getRouter().navTo("EditarPlataformas",{id:a})},onSearch:function(t){var a=[];var e=t.getSource().getValue();if(e&&e.length>0){var r=new o("nome",s.Contains,e);a.push(r)}var i=this.byId("tablePlataformas");var n=i.getBinding("items");n.filter(a,"Application")}})});
},
	"desafio/l4e/app/controller/Menu.controller.js":function(){sap.ui.define(["./BaseController"],function(t){"use strict";return t.extend("desafio.l4e.app.controller.Menu",{onInit:function(){},onNavConsultaPlataformas:function(){this.getRouter().navTo("ConsultaPlataformas")},onNavCadastroPlataformas:function(){this.getRouter().navTo("CadastroPlataformas")},onItemSelect:function(t){var e=t.getParameter("item");console.log(e);console.log(this.byId("menu").getParameter().sId())},onMenuButtonPress:function(){var t=this.byId("toolPage");t.setSideExpanded(!t.getSideExpanded())}})});
},
	"desafio/l4e/app/i18n/i18n.properties":'title=Title\nappTitle=App\nappDescription=App Description\n',
	"desafio/l4e/app/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"desafio.l4e.app","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","ach":"ach","sourceTemplate":{"id":"html5moduletemplates.basicSAPUI5ApplicationProjectModule","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"desafio.l4e.app.view.App","type":"XML","async":true,"id":"App"},"dependencies":{"minUI5Version":"1.60.1","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{},"sap.tnt":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"desafio.l4e.app.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"desafio.l4e.app.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteApp","pattern":"RouteApp","target":["TargetApp"]},{"name":"Menu","pattern":"","target":["Menu","CadastroPlataformas"]},{"name":"CadastroPlataformas","pattern":"CadastroPlataformas","target":["Menu","CadastroPlataformas"]},{"name":"ConsultaPlataformas","pattern":"ConsultaPlataformas","target":["Menu","ConsultaPlataformas"]},{"name":"EditarPlataformas","pattern":"EditarPlataformas/{id}","target":["Menu","CadastroPlataformas"]}],"targets":{"Menu":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"menu","viewName":"Menu","controlAggregation":"masterPages"},"TargetApp":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"App","viewName":"App"},"CadastroPlataformas":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"cadastroplataformas","viewName":"CadastroPlataformas","controlAggregation":"detailPages"},"ConsultaPlataformas":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"consultaplataformas","viewName":"ConsultaPlataformas","controlAggregation":"detailPages"}}}}}',
	"desafio/l4e/app/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"desafio/l4e/app/view/App.view.xml":'<mvc:View xmlns:layout="sap.ui.layout" xmlns:smartmultiedit="sap.ui.comp.smartmultiedit" \nxmlns:f="sap.f" \ncontrollerName="desafio.l4e.app.controller.App" \nxmlns:mvc="sap.ui.core.mvc" \ndisplayBlock="true" \nxmlns="sap.m"\nxmlns:tnt="sap.tnt" ><SplitApp id="app"></SplitApp></mvc:View>\n',
	"desafio/l4e/app/view/CadastroPlataformas.view.xml":'<mvc:View xmlns:core="sap.ui.core" \ncontrollerName="desafio.l4e.app.controller.CadastroPlataformas" \nxmlns:form="sap.ui.layout.form" \nxmlns:mvc="sap.ui.core.mvc" \ndisplayBlock="true" \nxmlns="sap.m"><Page showHeader="true" title="Cadastro de Plataformas" titleAlignment="Center"><content><form:Form ><form:title><core:Title text="Preencha os campos necessários" level="H5" ></core:Title></form:title><form:layout><form:ColumnLayout columnsL="2" columnsM="2" columnsXL="4" ></form:ColumnLayout></form:layout><form:formContainers><form:FormContainer ><form:formElements><form:FormElement ><form:label><Label text="Nome" design="Bold" ></Label></form:label><form:fields><Input value="{Plataformas>/nome}" ></Input></form:fields></form:FormElement><form:FormElement ><form:label><Label text="status" design="Bold"></Label></form:label><form:fields><Switch type="AcceptReject" change="onChangeSwitch" state="{= ${Plataformas>/status} === \'A\' ? true : false}" ></Switch></form:fields></form:FormElement></form:formElements></form:FormContainer></form:formContainers></form:Form></content><footer><OverflowToolbar ><ToolbarSpacer /><Button text="Confirmar" type="Accept" press="onConfirmar" /><Button text="Cancelar" type="Reject" press="onCancelar"/></OverflowToolbar></footer></Page></mvc:View>',
	"desafio/l4e/app/view/ConsultaPlataformas.view.xml":'<mvc:View xmlns:layout="sap.ui.layout" xmlns:smartmultiedit="sap.ui.comp.smartmultiedit" \nxmlns:f="sap.f" \ncontrollerName="desafio.l4e.app.controller.ConsultaPlataformas" \nxmlns:mvc="sap.ui.core.mvc" \ndisplayBlock="true" \nxmlns="sap.m"\nxmlns:tnt="sap.tnt" ><Page showHeader="true" title="Consulta de Plataformas" titleAlignment="Center"><content><Table mode="Delete" id="tablePlataformas" delete="onExcluir" items="{path: \'Plataformas>/\'}" ><headerToolbar><OverflowToolbar ><content><Title text="Plataformas" level="H2"></Title><ToolbarSpacer ></ToolbarSpacer><SearchField placeholder="Buscar por plataforma" width="50%" liveChange="onSearch"></SearchField></content></OverflowToolbar></headerToolbar><columns><Column demandPopin="true" minScreenWidth="Desktop" ><Label wrapping="true" text="ID" design="Bold" ></Label></Column><Column demandPopin="true" minScreenWidth="Desktop" ><Label wrapping="true" text="Nome" design="Bold" ></Label></Column><Column demandPopin="true" minScreenWidth="Desktop" ><Label wrapping="true" text="Data de Criação" design="Bold" ></Label></Column><Column demandPopin="true" minScreenWidth="Desktop" ><Label wrapping="true" text="Data de Atualização" design="Bold" ></Label></Column><Column demandPopin="true" minScreenWidth="Desktop" ><Label wrapping="true" text="Status" design="Bold" ></Label></Column></columns><items><ColumnListItem type="Detail" detailPress="onNavEditarPlataforma" ><cells><Text text="{Plataformas>id}" ></Text><Text text="{Plataformas>nome}"></Text><Text text="{Plataformas>criado}"></Text><Text text="{Plataformas>atualizado}"></Text><ObjectStatus text="{= ${Plataformas>status} === \'A\' ? \'Ativo\' : \'Inativo\'}" inverted="true" state="{= ${Plataformas>status} === \'A\' ? \'Success\' : \'Error\'}"></ObjectStatus></cells></ColumnListItem></items></Table></content></Page></mvc:View>\n',
	"desafio/l4e/app/view/Menu.view.xml":'<mvc:View \nxmlns:f="sap.f" \ncontrollerName="desafio.l4e.app.controller.Menu" \nxmlns:mvc="sap.ui.core.mvc" \ndisplayBlock="true" \nxmlns="sap.m"\nxmlns:tnt="sap.tnt" ><f:ShellBar\n        id="menu"\n        title="Desafio L4E"\n        secondTitle="SAPUI5" ><f:menu><Menu ><MenuItem text="Cadastro de Plataformas" icon="sap-icon://add-contact" press="onNavCadastroPlataformas" ></MenuItem><MenuItem text="Consulta de Plataformas" icon="sap-icon://account" press="onNavConsultaPlataformas"></MenuItem></Menu></f:menu></f:ShellBar><Page showHeader="false" ><content><VBox width="100%"><Image src="./images/sap.png" width="100%" height="100%"/></VBox></content></Page></mvc:View>'
}});
